/*
 * Assessment M3-A1: Software Engineering (Intro to Programming)
 * Section D — AI-Augmented Learning
 * Step 1: AI's Original Code (Before Human Debugging)
 *
 * Generated by AI Assistant based on prompt.
 * Contains edge-case flaws in floating-point equality and input handling.
 */

#include <stdio.h>

#define SIZE 10

int main() {
    int arr[SIZE];
    int sum = 0;
    int min, max;
    float mean;
    int i, j, temp;

    printf("Enter 10 integers:\n");
    for (i = 0; i < SIZE; i++) {
        printf("Enter integer %d: ", i + 1);
        scanf("%d", &arr[i]);
        sum += arr[i];
    }

    // Initialize min and max
    min = arr[0];
    max = arr[0];
    for (i = 1; i < SIZE; i++) {
        if (arr[i] < min) {
            min = arr[i];
        }
        if (arr[i] > max) {
            max = arr[i];
        }
    }

    // Calculate mean
    mean = (float)sum / SIZE;

    // Display statistics
    printf("\n--- Results ---\n");
    printf("Minimum value : %d\n", min);
    printf("Maximum value : %d\n", max);
    printf("Arithmetic Mean: %.2f\n", mean);

    // Bubble sort ascending
    for (i = 0; i < SIZE - 1; i++) {
        for (j = 0; j < SIZE - i - 1; j++) {
            if (arr[j] > arr[j + 1]) {
                temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }

    // Display sorted list
    printf("Sorted array (ascending): ");
    for (i = 0; i < SIZE; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");

    // Check proximity to min or max
    // [BUG / FLAW]: Direct floating-point equality comparison (diff_min == diff_max)
    // fails in IEEE-754 floating point arithmetic due to precision roundoff,
    // and fails when all 10 values are identical (min == max == mean).
    float diff_min = mean - min;
    float diff_max = max - mean;

    if (diff_min < diff_max) {
        printf("The mean is closer to the minimum value.\n");
    } else if (diff_max < diff_min) {
        printf("The mean is closer to the maximum value.\n");
    } else {
        printf("The mean is exactly midway between the minimum and maximum.\n");
    }

    return 0;
}
